### ISSUE TITLE
Peering Request

### ISSUE THREAD

**Issue by andrecasas** [routeviews/public-issues#130]
### Full Name

AdylNET Telecom

### ASN

28283

### PeeringDB Integration

- [X] My PeeringDB Entries are current
- [ ] Peer at **ALL EXCHANGES** (*and skip the Peer Address(es) field below*)

### Peer Address(es)

80.249.214.120
2001:7f8:1::a502:8283:1
80.81.194.199
2001:7f8::6e7b:0:1
206.126.237.190
2001:504:0:2:0:2:8283:1
206.41.108.56
2001:504:40:108::1:56
187.16.220.93
2001:12f8::220:93
45.68.17.30
2801:14:9000::2:8283:1

### Multihop

- [ ] Multihop Peering Request

**Comment by pfsinoz** [comment]
Thanks for contributing to the RouteViews project! 

We are able to support additional peerings with AS28283 at PIT.SCL and AMSIX.AMS only due to resource constraints at the other requested locations.

We've configured the following EBGP sessions on the PIT.SCL RouteViews collector:  
  
- asn:  6447  
- ipv4: 45.68.17.253  
- ipv6: 2801:14:9000::6447:1  
- fqdn: pit.scl.routeviews.org  
  
Relevant `show bgp summary` output:  
```  
pit.scl# sh bgp sum | include 28283
Neighbor                V         AS   MsgRcvd   MsgSent   TblVer  InQ OutQ  Up/Down State/PfxRcd   PfxSnt Desc  
45.68.17.30             4      28283         0         1        0    0    0    never       Active        0 AdylNET Telecom
2801:14:9000::2:8283:1  4      28283         0         1        0    0    0    never       Active        0 AdylNET Telecom  
```  

We've configured the following EBGP sessions on the AMSIX.AMS RouteViews collector:  
  
- asn:  6447  
- ipv4: 80.249.213.84/21
- ipv6: 2001:7f8:1::a500:6447:2/64  
- fqdn: amsix.ams.routeviews.org  
  
Relevant `show bgp summary` output:  
```  

amsix.ams# sh bgp sum | include 28283
Neighbor                    V         AS   MsgRcvd   MsgSent   TblVer  InQ OutQ  Up/Down State/PfxRcd   PfxSnt Desc  
80.249.214.120              4      28283         0         0        0    0    0    never       Active        0 AdylNET Telecom
2001:7f8:1::a502:8283:1     4      28283         0         0        0    0    0    never       Active        0 AdylNET Telecom  
```  
Please filter out default route and RFC6490 address space.  
  
NOTE: we do not accept addpath-RX or TX on connections.

Many thanks! :-)
